server:
  port: ":8081"


services:
  name: "order_service"

mongo:
  string: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.7"

redis:
  clusterMode: false
  hosts: "127.0.0.1:6379"
  db: 1

onlineKafka:
  brokers:
    - "localhost:9092"
  clientId: "tenant-service"
  version: 2.0.0

consumers:
  orders:
    topic: "omniful.order-service.order.create-events"
    groupId: "1"
    enabled: false
